Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0ed9277fb7eb570c9 # Amazon Linux AMI in N.Virginia
      KeyName: oleh
      SecurityGroups:
        - !Ref SSHSecurityGroup
      UserData:
        'Fn::Base64':
          !Sub |
          #!/bin/bash -xe
          sudo yum install ec2-instance-connect
          sudo yum update -y
          sudo amazon-linux-extras install ansible2 -y
  Ec2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0ed9277fb7eb570c9 # Amazon Linux AMI in N.Virginia
      KeyName: oleh
      SecurityGroups:
        - !Ref SSHSecurityGroup
      UserData:
        'Fn::Base64':
          !Sub |
          #!/bin/bash -xe
          sudo yum install ec2-instance-connect
          sudo yum update -y
   